package:
  name: dnspython
  version: !!str 1.11.1

source:
  fn: dnspython-1.11.1.zip
  url: https://pypi.python.org/packages/source/d/dnspython/dnspython-1.11.1.zip
  md5: 5829130ed557d6f2e1c3ca9ed01d337a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dnspython = dnspython:main
    #
    # Would create an entry point called dnspython that calls dnspython.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - dns
    - dns.rdtypes
    - dns.rdtypes.ANY
    - dns.rdtypes.IN

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.dnspython.org
  license: http://www.dnspython.org/LICENSE
  summary: 'A DNS toolkit for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
