package:
  name: parquet-python

source:
  git_tag: master
  git_url: https://github.com/jcrobak/parquet-python.git

requirements:
  build:
    - python
    - python-snappy
    - thrift
    - setuptools

  run:
    - python

test:
  imports:
    - parquet

