package:
    name: libgcrypt
    version: "1.8.1"

source:
    fn: libgcrypt-1.8.1.tar.bz2
    url: https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.1.tar.bz2
    md5: b21817f9d850064d2177285f1073ec55

requirements:
    build:
        - libgpg-error 1.27

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: https://gnupg.org/software/libgcrypt/index.html
    license: GNU Lesser General Public License (LGPLv2.1+)
    summary: 'Crypo Library'
