package:
  name: nosy
  version: !!str 1.1.2

source:
  hg_url: https://bitbucket.org/douglatornell/nosy
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nosy = nosy:main
    #
    # Would create an entry point called nosy that calls nosy.main()

    - nosy = nosy.nosy:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - nosy

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - nosy --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://douglatornell.ca/software/python/Nosy/
  license:  BSD License
  summary: 'Run the nose test discovery and execution tool whenever a source file\nis changed.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
