package:
  name: django-treebeard
  version: "4.0.1"

source:
  fn: django-treebeard-4.0.1.tar.gz
  url: https://pypi.python.org/packages/c5/a2/0df0c2e11113a68d3ff6438e497382ad738aa2664e32aabe044a0266a0f8/django-treebeard-4.0.1.tar.gz
  md5: a96c72c186d7aea7142fe5673b96b3be
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-treebeard = django-treebeard:main
    #
    # Would create an entry point called django-treebeard that calls django-treebeard.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - django >=1.7

  run:
    - python
    - django >=1.7

test:
  # Python imports
  imports:
    - treebeard
    - treebeard.templatetags
    - treebeard.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://tabo.pe/projects/django-treebeard/
  license: Apache Software License
  summary: 'Efficient tree implementations for Django 1.7+'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
