package:
  name: python-social-auth
  version: "0.2.19"

source:
  fn: python-social-auth-0.2.19.tar.gz
  url: https://pypi.python.org/packages/72/4c/5fb6c9157eb059e662beafbc73c84030741ea30eaaa643ca1cb8b58f1bdc/python-social-auth-0.2.19.tar.gz
  md5: 65b9c0b77ca2870b5dc586a0c65a0eba
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-social-auth = python-social-auth:main
    #
    # Would create an entry point called python-social-auth that calls python-social-auth.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-openid >=2.2.5
    - requests >=2.9.1
    - oauthlib >=1.0.3
    - requests-oauthlib >=0.6.1
    - six >=1.10.0
    - pyjwt >=1.4.0

  run:
    - python
    - python-openid >=2.2.5
    - requests >=2.9.1
    - oauthlib >=1.0.3
    - requests-oauthlib >=0.6.1
    - six >=1.10.0
    - pyjwt >=1.4.0

test:
  # Python imports
  imports:
    - social
    - social.apps
    - social.backends
    - social.pipeline
    - social.storage
    - social.strategies

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage >=3.6
#    - httpretty ==0.6.5
    - mock ==1.0.1
    - nose >=1.2.1
    - pyjwt >=1.0.0,<2.0.0
#    - python-saml ==2.1.3
#    - rednose >=0.4.1
    - requests >=1.1.0
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/omab/python-social-auth
  license: BSD License
  summary: 'Python social authentication made simple.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
