package:
  name: pytest-django
  version: "2.9.1"

source:
  fn: pytest-django-2.9.1.tar.gz
  url: https://pypi.python.org/packages/50/6d/77a4644d15746ed2a243ed557af693cec7887e43b357919ba0b4fd029518/pytest-django-2.9.1.tar.gz
  md5: 3c9dde85e99ec409df209a62b4715e1a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-django = pytest-django:main
    #
    # Would create an entry point called pytest-django that calls pytest-django.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytest >=2.5

  run:
    - python
    - setuptools
    - pytest >=2.5

test:
  # Python imports
  imports:
    - pytest_django

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD License
  summary: 'A Django plugin for py.test.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
