package:
  name: rednose
  version: "1.1.1"

source:
  fn: rednose-1.1.1.tar.gz
  url: https://pypi.python.org/packages/05/82/016ee67c42c0083a106e7049532bfcf3f0ea434972251ec44a62f31700ea/rednose-1.1.1.tar.gz
  md5: ec7693bac9d95f901737006ab2b0b1b0
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rednose = rednose:main
    #
    # Would create an entry point called rednose that calls rednose.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - setuptools
    - python-termstyle >=0.1.7
    - colorama

  run:
    - python
    - setuptools
    - setuptools
    - python-termstyle >=0.1.7
    - colorama

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/JBKahn/rednose
  license: BSD License
  summary: 'coloured output for nosetests'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
