{% set name = "kafka-python" %}
{% set version = "1.3.4" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a84d9635e3a4d5054c342ad6e5b338f9438fbcac810b677a2f6da68a51fb66a8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - kafka
    - kafka.consumer
    - kafka.coordinator
    - kafka.coordinator.assignors
    - kafka.metrics
    - kafka.metrics.stats
    - kafka.partitioner
    - kafka.producer
    - kafka.protocol
    - kafka.serializer
    - kafka.vendor
#  requires:
#    - mock
    #- tox

about:
  home: https://github.com/dpkp/kafka-python
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: Pure Python client for Apache Kafka
  description: "Kafka Python client\n------------------------\n\n.. image:: https://img.shields.io/badge/kafka-0.10%2C%200.9%2C%200.8.2%2C%200.8.1%2C%200.8-brightgreen.svg\n    :target: https://kafka-python.readthedocs.io/compatibility.html\n\
    .. image:: https://img.shields.io/pypi/pyversions/kafka-python.svg\n    :target: https://pypi.python.org/pypi/kafka-python\n.. image:: https://coveralls.io/repos/dpkp/kafka-python/badge.svg?branch=master&service=github\n\
    \    :target: https://coveralls.io/github/dpkp/kafka-python?branch=master\n.. image:: https://travis-ci.org/dpkp/kafka-python.svg?branch=master\n    :target: https://travis-ci.org/dpkp/kafka-python\n\
    .. image:: https://img.shields.io/badge/license-Apache%202-blue.svg\n    :target: https://github.com/dpkp/kafka-python/blob/master/LICENSE\n\nPython client for the Apache Kafka distributed stream processing\
    \ system.\nkafka-python is designed to function much like the official java client, with a\nsprinkling of pythonic interfaces (e.g., consumer iterators).\n\nkafka-python is best used with newer brokers\
    \ (0.10 or 0.9), but is backwards-compatible with\nolder versions (to 0.8.0). Some features will only be enabled on newer brokers,\nhowever; for example, fully coordinated consumer groups -- i.e., dynamic\
    \ partition\nassignment to multiple consumers in the same group -- requires use of 0.9+ kafka\nbrokers. Supporting this feature for earlier broker releases would require\nwriting and maintaining custom\
    \ leadership election and membership / health\ncheck code (perhaps using zookeeper or consul). For older brokers, you can\nachieve something similar by manually assigning different partitions to each\n\
    consumer instance with config management tools like chef, ansible, etc. This\napproach will work fine, though it does not support rebalancing on failures.\nSee <https://kafka-python.readthedocs.io/en/master/compatibility.html>\n\
    for more details.\n\nPlease note that the master branch may contain unreleased features. For release\ndocumentation, please see readthedocs and/or python's inline help.\n\n>>> pip install kafka-python\n\
    \nKafkaConsumer\n*************\n\nKafkaConsumer is a high-level message consumer, intended to operate as similarly\nas possible to the official java client. Full support for coordinated\nconsumer groups\
    \ requires use of kafka brokers that support the Group APIs: kafka v0.9+.\n\nSee <https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html>\nfor API and configuration details.\n\nThe\
    \ consumer iterator returns ConsumerRecords, which are simple namedtuples\nthat expose basic message attributes: topic, partition, offset, key, and value:\n\n>>> from kafka import KafkaConsumer\n>>>\
    \ consumer = KafkaConsumer('my_favorite_topic')\n>>> for msg in consumer:\n...     print (msg)\n\n>>> # join a consumer group for dynamic partition assignment and offset commits\n>>> from kafka import\
    \ KafkaConsumer\n>>> consumer = KafkaConsumer('my_favorite_topic', group_id='my_favorite_group')\n>>> for msg in consumer:\n...     print (msg)\n\n>>> # manually assign the partition list for the consumer\n\
    >>> from kafka import TopicPartition\n>>> consumer = KafkaConsumer(bootstrap_servers='localhost:1234')\n>>> consumer.assign([TopicPartition('foobar', 2)])\n>>> msg = next(consumer)\n\n>>> # Deserialize\
    \ msgpack-encoded values\n>>> consumer = KafkaConsumer(value_deserializer=msgpack.loads)\n>>> consumer.subscribe(['msgpackfoo'])\n>>> for msg in consumer:\n...     assert isinstance(msg.value, dict)\n\
    \n\nKafkaProducer\n*************\n\nKafkaProducer is a high-level, asynchronous message producer. The class is\nintended to operate as similarly as possible to the official java client.\nSee <https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html>\n\
    for more details.\n\n>>> from kafka import KafkaProducer\n>>> producer = KafkaProducer(bootstrap_servers='localhost:1234')\n>>> for _ in range(100):\n...     producer.send('foobar', b'some_message_bytes')\n\
    \n>>> # Block until a single message is sent (or timeout)\n>>> future = producer.send('foobar', b'another_message')\n>>> result = future.get(timeout=60)\n\n>>> # Block until all pending messages are\
    \ at least put on the network\n>>> # NOTE: This does not guarantee delivery or success! It is really\n>>> # only useful if you configure internal batching using linger_ms\n>>> producer.flush()\n\n>>>\
    \ # Use a key for hashed-partitioning\n>>> producer.send('foobar', key=b'foo', value=b'bar')\n\n>>> # Serialize json messages\n>>> import json\n>>> producer = KafkaProducer(value_serializer=lambda v:\
    \ json.dumps(v).encode('utf-8'))\n>>> producer.send('fizzbuzz', {'foo': 'bar'})\n\n>>> # Serialize string keys\n>>> producer = KafkaProducer(key_serializer=str.encode)\n>>> producer.send('flipflap',\
    \ key='ping', value=b'1234')\n\n>>> # Compress messages\n>>> producer = KafkaProducer(compression_type='gzip')\n>>> for i in range(1000):\n...     producer.send('foobar', b'msg %d' % i)\n\nThread safety\n\
    *************\n\nThe KafkaProducer can be used across threads without issue, unlike the\nKafkaConsumer which cannot.\n\nWhile it is possible to use the KafkaConsumer in a thread-local manner,\nmultiprocessing\
    \ is recommended.\n\nCompression\n***********\n\nkafka-python supports gzip compression/decompression natively. To produce or consume lz4 \ncompressed messages, you should install python-lz4 (pip install\
    \ lz4). \nTo enable snappy compression/decompression install python-snappy (also requires snappy library).\nSee <https://kafka-python.readthedocs.io/en/master/install.html#optional-snappy-install>\n\
    for more information.\n\nProtocol\n********\n\nA secondary goal of kafka-python is to provide an easy-to-use protocol layer\nfor interacting with kafka brokers via the python repl. This is useful for\n\
    testing, probing, and general experimentation. The protocol support is\nleveraged to enable a KafkaClient.check_version() method that\nprobes a kafka broker and attempts to identify which version it\
    \ is running\n(0.8.0 to 0.10).\n\n\nLow-level\n*********\n\nLegacy support is maintained for low-level consumer and producer classes,\nSimpleConsumer and SimpleProducer. See\n<https://kafka-python.readthedocs.io/en/master/simple.html?highlight=SimpleProducer>\
    \ for API details.\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
