package:
  name: docker-py
  version: !!str 0.7.2

source:
  fn: docker-py-0.7.2.tar.gz
  url: https://pypi.python.org/packages/source/d/docker-py/docker-py-0.7.2.tar.gz
  md5: 242068d6282a54e1452e920ff007bad0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - docker-py = docker-py:main
    #
    # Would create an entry point called docker-py that calls docker-py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.2.1,<2.5.0
    - six >=1.3.0
    - websocket-client >=0.11.0

  run:
    - python
    - requests >=2.2.1,<2.5.0
    - six >=1.3.0
    - websocket-client >=0.11.0

test:
  # Python imports
  imports:
    - docker
    - docker.auth
    - docker.ssladapter
    - docker.unixconn
    - docker.utils

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: UNKNOWN
  license:  Apache Software License
  summary: 'Python client for Docker.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
