package:
  name: django-taggit
  version: "0.18.1"

source:
  fn: django-taggit-0.18.1.tar.gz
  url: https://pypi.python.org/packages/fb/a7/0c966b619a3a5000969a24f3769751f3426b9511d561974a79e8b92b54b9/django-taggit-0.18.1.tar.gz
  md5: 02b078c909b41d5daa36820013f4e2b7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-taggit = django-taggit:main
    #
    # Would create an entry point called django-taggit that calls django-taggit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - taggit

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/alex/django-taggit/tree/master
  license: BSD License
  summary: 'django-taggit is a reusable Django application for simple tagging.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
