package:
  name: pylibpcap
  version: !!str 0.6.4

source:
  fn: pylibpcap-0.6.4.tar.gz
  url: http://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
  md5: 7ebcaa72f998f85744be226b91d88aa3
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - funcy = funcy:main
    #
    # Would create an entry point called funcy that calls funcy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pcap

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pylibpcap.sourceforge.net/
  license:  BSD License
  summary: 'pylibpcap is a python module for the libpcap packet capture library.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
