package:
  name: cqlengine
  version: !!str 0.19.0

source:
  fn: cqlengine-0.19.0.tar.gz
  url: https://pypi.python.org/packages/source/c/cqlengine/cqlengine-0.19.0.tar.gz
  md5: eba1a8224861f07d9b6dbdc12fe94dad
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cqlengine = cqlengine:main
    #
    # Would create an entry point called cqlengine that calls cqlengine.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cassandra-driver >=2.1.0
    - six >=1.7.2

  run:
    - setuptools
    - python
    - cassandra-driver >=2.1.0
    - six >=1.7.2

test:
  # Python imports
  imports:
    - cqlengine
    - cqlengine.tests
    - cqlengine.tests.columns
    - cqlengine.tests.connections
    - cqlengine.tests.management
    - cqlengine.tests.model
    - cqlengine.tests.operators
    - cqlengine.tests.query
    - cqlengine.tests.statements

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cqlengine/cqlengine
  license:  BSD License
  summary: 'Cassandra CQL 3 Object Mapper for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
