package:
  name: xmlsec
  version: "1.3.3"

source:
  fn: xmlsec-1.3.3.tar.gz
  url: https://pypi.python.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
  md5: d28142c7a547f859f2f4248265b16f86
  patches:
   # List any patch files here
    - xmlsec_setupinfo.py.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - xmlsec = xmlsec:main
    #
    # Would create an entry point called xmlsec that calls xmlsec.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python >=3.5
    - setuptools
    - pkgconfig
    - lxml >=3.0
    - libxmlsec1 1.2.20

  run:
    - python >=3.5
    - pkgconfig
    - lxml >=3.0
    - libxmlsec1 1.2.20

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT License
  summary: 'Python bindings for the XML Security Library'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
