package:
  name: scapy
  version: !!str 2.2.0.1

source:
  fn: scapy-2.2.0-dev.tar.gz
  url: https://pypi.python.org/packages/source/s/scapy/scapy-2.2.0-dev.tar.gz
  md5: 1a5115d1f33548501d01d735bd689f13
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scapy = scapy:main
    #
    # Would create an entry point called scapy that calls scapy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pcapy

  run:
    - python
    - pcapy

test:
  # Python imports
  imports:
    - scapy
#    - scapy.arch
#    - scapy.asn1
#    - scapy.contrib
#    - scapy.crypto
#    - scapy.layers
#    - scapy.modules
#    - scapy.tools

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.secdev.org/projects/scapy
  license:  GNU General Public License v2 (GPLv2)
  summary: 'Scapy: interactive packet manipulation tool'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
