package:
  name: paramiko
  version: !!str 1.12.1

source:
  fn: paramiko-1.12.1.tar.gz
  url: https://pypi.python.org/packages/source/p/paramiko/paramiko-1.12.1.tar.gz
  md5: ae4544dc0a1419b141342af89fcf0dd9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - paramiko = paramiko:main
    #
    # Would create an entry point called paramiko that calls paramiko.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pycrypto >=2.1,!=2.4
    - ecdsa

  run:
    - python
    - pycrypto >=2.1,!=2.4
    - ecdsa

test:
  # Python imports
  imports:
    - paramiko

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/paramiko/paramiko/
  license:  GNU Library or Lesser General Public License (LGPL)
  summary: 'SSH2 protocol library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
