package:
    name: root
    version: 5.34.14

source:
    git_url: https://github.com/root-mirror/root
    git_tag: v5-34-21

build:
    number: 0

requirements:
    build:
        - python
        - openssl
        - qt
        - sqlite
        - fftw

    run:
        - python
        - openssl
        - qt
        - sqlite
        - fftw

test:
    imports:
        - ROOT

    commands:

about:
    home: http://root.cern.ch/
    license: LGPL v2.1
