package:
  name: djangorestframework
  version: !!str 3.0.4

source:
  fn: djangorestframework-3.0.4.tar.gz
  url: https://pypi.python.org/packages/source/d/djangorestframework/djangorestframework-3.0.4.tar.gz
  md5: f83a8519ac4af476914a30783f9e2cf7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - djangorestframework = djangorestframework:main
    #
    # Would create an entry point called djangorestframework that calls djangorestframework.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.templatetags
    - rest_framework.utils

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.django-rest-framework.org
  license:  BSD License
  summary: 'Web APIs for Django, made easy.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
