package:
  name: pygraphviz
  version: !!str 1.2

source:
  fn: pygraphviz-1.2.zip
  url: https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.2.zip
  md5: 90c728a8db276eede4e3af2f990a8985
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pygraphviz = pygraphviz:main
    #
    # Would create an entry point called pygraphviz that calls pygraphviz.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - graphviz

  run:
    - python
    - graphviz

test:
  # Python imports
  imports:
    - pygraphviz
    - pygraphviz.tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pygraphviz.github.io
  license:  BSD License
  summary: 'Python interface to Graphviz'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
