package:
  name: root_numpy
  version: !!str 3.3.1

source:
  fn: root_numpy-3.3.31.tar.gz
  url: https://pypi.python.org/packages/source/r/root_numpy/root_numpy-3.3.1.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rootpy = rootpy:main
    #
    # Would create an entry point called rootpy that calls rootpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytables

  run:
    - python
    - setuptools
    - pytables

test:
  # Python imports
  imports:
    - root_numpy

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
