{% set name = "builder" %}
{% set version = "0.2.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "30508cf662e07ae47020782e3227fcc578148b827d530d8f1f36f1d2ea8e8a52" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/mhworth/builder
  git_rev: v{{version}}

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - python-dateutil
    - arrow >=0.4.3
    - networkx >=1.8.1
    - tornado >=3.2.2
  run:
    - python
    - python-dateutil
    - arrow >=0.4.3
    - networkx >=1.8.1
    - tornado >=3.2.2

test:
  imports:
    - builder
    - builder.tests

about:
  home: http://github.com/mhworth/builder
  license: MIT
  license_family: OTHER
  license_file: ''
  summary: A framework for building batch processing pipelines
  description: A framework for building batch processing pipelines
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
