package:
  name: willow
  version: "0.3"

source:
  fn: Willow-0.3.tar.gz
  url: https://pypi.python.org/packages/cb/58/976c9b52b7ea52c81fc7dc02cfda1b7294b6dc243ceb46227709b3ed5c47/Willow-0.3.tar.gz
  md5: 259aa2e66344a2818eb676f828d9b2e1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - willow = willow:main
    #
    # Would create an entry point called willow that calls willow.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - tests
    - willow
    - willow.plugins
    - willow.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: 
  license: BSD License
  summary: 'A Python image library that sits on top of Pillow, Wand and OpenCV'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
