package:
  name: networkx
  version: !!str 1.8.1

source:
  fn: networkx-1.8.1.zip
  url: https://pypi.python.org/packages/source/n/networkx/networkx-1.8.1.zip
  md5: 4a90328898d9db29bbb12ef3e6223bab
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - networkx = networkx:main
    #
    # Would create an entry point called networkx that calls networkx.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - networkx
    - networkx.algorithms
    - networkx.algorithms.approximation
    - networkx.algorithms.assortativity
    - networkx.algorithms.bipartite
    - networkx.algorithms.centrality
    - networkx.algorithms.chordal
    - networkx.algorithms.community
    - networkx.algorithms.components
    - networkx.algorithms.connectivity
    - networkx.algorithms.flow
    - networkx.algorithms.isomorphism
    - networkx.algorithms.link_analysis
    - networkx.algorithms.operators
    - networkx.algorithms.shortest_paths
    - networkx.algorithms.traversal
    - networkx.classes
    - networkx.drawing
    - networkx.external
    - networkx.external.decorator
    - networkx.external.decorator.decorator2
    - networkx.generators
    - networkx.linalg
    - networkx.readwrite
    - networkx.readwrite.json_graph
    - networkx.utils

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://networkx.lanl.gov/
  license:  BSD License
  summary: 'Python package for creating and manipulating graphs and networks'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
