package:
  name: nose-timer
  version: !!str 0.4.3

source:
  fn: nose-timer-0.4.3.tar.gz
  url: https://pypi.python.org/packages/source/n/nose-timer/nose-timer-0.4.3.tar.gz
  md5: e1a8e80b67734501fcca6f5927fc23b1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nose-timer = nose-timer:main
    #
    # Would create an entry point called nose-timer that calls nose-timer.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - nose
    - termcolor

  run:
    - python
    - nose
    - termcolor

test:
  # Python imports
  imports:
    - nosetimer

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mahmoudimus/nose-timer
  license:  BSD License or  MIT License
  summary: 'A timer plugin for nosetests'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
