package:
  name: salt
  version: !!str 2014.1.7

source:
  fn: salt-2014.1.7.tar.gz
  url: https://pypi.python.org/packages/source/s/salt/salt-2014.1.7.tar.gz
  md5: 9ab50536f46389983888771d4e735d56
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - salt = salt:main
    #
    # Would create an entry point called salt that calls salt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - jinja2
    - m2crypto
    - msgpack-python
    - pycrypto
    - pyyaml
    - pyzmq >=2.2.0
    - markupsafe
    - apache-libcloud

  run:
    - python
    - jinja2
    - m2crypto
    - msgpack-python
    - pycrypto
    - pyyaml
    - pyzmq >=2.2.0
    - markupsafe
    - apache-libcloud

test:
  # Python imports
  imports:
    - salt
    - salt.auth
    - salt.cli
    - salt.client
    - salt.client.ssh
    - salt.client.ssh.wrapper
    - salt.cloud
    - salt.cloud.clouds
    - salt.ext
    - salt.fileserver
    - salt.grains
    - salt.log
    - salt.log.handlers
    - salt.modules
    - salt.output
    - salt.pillar
    - salt.renderers
    - salt.returners
    - salt.roster
    - salt.runners
    - salt.search
    - salt.states
    - salt.templates # [linux]
    - salt.tops
    - salt.transport
    - salt.utils
    - salt.utils.decorators
    - salt.utils.validate
    - salt.wheel

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://saltstack.org
  license:  Apache Software License
  summary: 'Portable, distributed, remote execution and configuration management system'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
