package:
  name: django-modelcluster
  version: "2.0"

source:
  fn: django-modelcluster-2.0.tar.gz
  url: https://pypi.python.org/packages/8f/d9/c64f188e796ca2614fd6d95e70eb135c96ffe806cc34b80a600dee68468d/django-modelcluster-2.0.tar.gz
  md5: 8980b6c8e405b9ee3ba871b3ebe7b8f8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-modelcluster = django-modelcluster:main
    #
    # Would create an entry point called django-modelcluster that calls django-modelcluster.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytz >=2015.2

  run:
    - python
    - pytz >=2015.2

test:
  # Python imports
  imports:
    - modelcluster
    - modelcluster.contrib

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/torchbox/django-modelcluster
  license: BSD License
  summary: "Django extension to allow working with 'clusters' of models as a single unit, independently of the database"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
