package:
  name: influxdb
  version: !!str 0.1.11

source:
  fn: influxdb-0.1.11.tar.gz
  url: https://pypi.python.org/packages/source/i/influxdb/influxdb-0.1.11.tar.gz
  md5: 1970db805e4e9597a1cb89d72cdcc5dc
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - influxdb = influxdb:main
    #
    # Would create an entry point called influxdb that calls influxdb.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=1.0.3

  run:
    - python
    - requests >=1.0.3

test:
  # Python imports
  imports:
    - influxdb

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: UNKNOWN
  license: MIT
  summary: 'influxdb client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
